import json
import re
import tempfile
from datetime import UTC, datetime
from pathlib import Path
from typing import Any
from uuid import UUID, uuid4

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


class LegalDocumentService:
    def __init__(self, artifact_directory: Path | None = None) -> None:
        self._artifact_directory = artifact_directory or Path(tempfile.gettempdir()) / "veritas-documents"
        self._artifact_directory.mkdir(parents=True, exist_ok=True)

    def generate_document(self, args: dict[str, Any]) -> dict[str, Any]:
        document_type = self._clean_text(args.get("documentType") or args.get("document_type") or "Legal Document")
        title = self._clean_text(args.get("title") or document_type)
        sections = self._parse_sections(args.get("sections"))
        if not sections:
            raise ValueError("At least one document section is required.")

        artifact_id = uuid4()
        filename = self._filename(document_type, title)
        pdf_path = self._pdf_path(artifact_id)
        generated_at = datetime.now(UTC)
        metadata = {
            "artifactId": str(artifact_id),
            "filename": filename,
            "contentType": "application/pdf",
            "downloadUrl": f"/api/v1/chat-artifacts/{artifact_id}",
            "description": f"{document_type} PDF generated by Veritas.",
            "generatedAt": generated_at.isoformat(),
        }

        self._build_pdf(
            pdf_path=pdf_path,
            document_type=document_type,
            title=title,
            sections=sections,
            generated_at=generated_at,
            metadata=self._document_metadata(args),
            parties=self._parse_text_list(args.get("parties")),
            signature_blocks=self._parse_text_list(args.get("signatureBlocks") or args.get("signature_blocks")),
        )
        self._metadata_path(artifact_id).write_text(json.dumps({**metadata, "path": str(pdf_path)}), encoding="utf-8")
        return {"artifact": metadata}

    def get_artifact(self, artifact_id: UUID) -> dict[str, str]:
        metadata_path = self._metadata_path(artifact_id)
        pdf_path = self._pdf_path(artifact_id)
        if not metadata_path.exists() or not pdf_path.exists():
            raise FileNotFoundError("Generated document was not found.")

        metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
        return {
            "path": str(pdf_path),
            "filename": str(metadata.get("filename") or "veritas-document.pdf"),
            "contentType": str(metadata.get("contentType") or "application/pdf"),
        }

    def _build_pdf(
        self,
        pdf_path: Path,
        document_type: str,
        title: str,
        sections: list[dict[str, str]],
        generated_at: datetime,
        metadata: list[tuple[str, str]],
        parties: list[str],
        signature_blocks: list[str],
    ) -> None:
        styles = self._styles()
        document = SimpleDocTemplate(
            str(pdf_path),
            pagesize=A4,
            rightMargin=20 * mm,
            leftMargin=20 * mm,
            topMargin=28 * mm,
            bottomMargin=24 * mm,
            title=title,
            author="Veritas",
        )
        story: list[Any] = [
            Paragraph("VERITAS LEGAL OPERATIONS", styles["Letterhead"]),
            Paragraph(document_type.upper(), styles["DocumentType"]),
            Paragraph(title, styles["Title"]),
            Spacer(1, 8 * mm),
        ]

        if metadata:
            story.append(self._metadata_table(metadata, styles))
            story.append(Spacer(1, 7 * mm))

        if parties:
            story.append(Paragraph("Parties", styles["SectionHeading"]))
            for party in parties:
                story.append(Paragraph(self._escape(party), styles["Body"]))
            story.append(Spacer(1, 5 * mm))

        story.append(
            Paragraph(
                "This document was generated as a formal draft from the information available to Veritas. "
                "It should be reviewed by qualified counsel before filing, signature, or service.",
                styles["Notice"],
            )
        )
        story.append(Spacer(1, 6 * mm))

        for index, section in enumerate(sections, start=1):
            if index > 1 and section.get("pageBreakBefore") == "true":
                story.append(PageBreak())
            heading = section["heading"]
            body = section["body"]
            story.append(Paragraph(f"{index}. {self._escape(heading)}", styles["SectionHeading"]))
            for paragraph in self._paragraphs(body):
                story.append(Paragraph(self._escape(paragraph), styles["Body"]))
                story.append(Spacer(1, 3 * mm))

        if signature_blocks:
            story.append(Spacer(1, 8 * mm))
            story.append(Paragraph("Execution / Approval", styles["SectionHeading"]))
            for signer in signature_blocks:
                story.append(Spacer(1, 8 * mm))
                story.append(Paragraph("________________________________________", styles["SignatureLine"]))
                story.append(Paragraph(self._escape(signer), styles["Body"]))

        footer_text = f"Generated by Veritas on {generated_at.strftime('%Y-%m-%d %H:%M UTC')}"
        document.build(story, onFirstPage=lambda canvas, doc: self._page_frame(canvas, footer_text), onLaterPages=lambda canvas, doc: self._page_frame(canvas, footer_text))

    def _page_frame(self, canvas: Any, footer_text: str) -> None:
        canvas.saveState()
        width, height = A4
        canvas.setStrokeColor(colors.HexColor("#182235"))
        canvas.setLineWidth(1.2)
        canvas.line(20 * mm, height - 18 * mm, width - 20 * mm, height - 18 * mm)
        canvas.setFillColor(colors.HexColor("#182235"))
        canvas.setFont("Helvetica-Bold", 9)
        canvas.drawString(20 * mm, height - 14 * mm, "VERITAS")
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.HexColor("#6b7280"))
        canvas.drawRightString(width - 20 * mm, 13 * mm, footer_text)
        canvas.drawString(20 * mm, 13 * mm, f"Page {canvas.getPageNumber()}")
        canvas.restoreState()

    def _styles(self) -> dict[str, ParagraphStyle]:
        sample_styles = getSampleStyleSheet()
        return {
            "Letterhead": ParagraphStyle(
                "Letterhead",
                parent=sample_styles["Normal"],
                alignment=TA_CENTER,
                textColor=colors.HexColor("#182235"),
                fontName="Helvetica-Bold",
                fontSize=9,
                leading=12,
                spaceAfter=4,
            ),
            "DocumentType": ParagraphStyle(
                "DocumentType",
                parent=sample_styles["Normal"],
                alignment=TA_CENTER,
                textColor=colors.HexColor("#6b7280"),
                fontName="Helvetica-Bold",
                fontSize=10,
                leading=13,
                spaceAfter=4,
            ),
            "Title": ParagraphStyle(
                "Title",
                parent=sample_styles["Title"],
                alignment=TA_CENTER,
                textColor=colors.HexColor("#111827"),
                fontName="Helvetica-Bold",
                fontSize=18,
                leading=23,
                spaceAfter=8,
            ),
            "SectionHeading": ParagraphStyle(
                "SectionHeading",
                parent=sample_styles["Heading2"],
                textColor=colors.HexColor("#111827"),
                fontName="Helvetica-Bold",
                fontSize=11,
                leading=15,
                spaceBefore=4,
                spaceAfter=5,
            ),
            "Body": ParagraphStyle(
                "Body",
                parent=sample_styles["BodyText"],
                alignment=TA_JUSTIFY,
                textColor=colors.HexColor("#1f2937"),
                fontName="Times-Roman",
                fontSize=10.5,
                leading=15,
            ),
            "Notice": ParagraphStyle(
                "Notice",
                parent=sample_styles["BodyText"],
                borderColor=colors.HexColor("#d1d5db"),
                borderPadding=8,
                borderWidth=0.5,
                backColor=colors.HexColor("#f9fafb"),
                textColor=colors.HexColor("#374151"),
                fontName="Helvetica",
                fontSize=8.5,
                leading=12,
            ),
            "SignatureLine": ParagraphStyle(
                "SignatureLine",
                parent=sample_styles["BodyText"],
                textColor=colors.HexColor("#111827"),
                fontName="Helvetica",
                fontSize=10,
                leading=12,
            ),
        }

    def _metadata_table(self, metadata: list[tuple[str, str]], styles: dict[str, ParagraphStyle]) -> Table:
        table_data = [
            [Paragraph(f"<b>{self._escape(label)}</b>", styles["Body"]), Paragraph(self._escape(value), styles["Body"])]
            for label, value in metadata
        ]
        table = Table(table_data, colWidths=[38 * mm, 112 * mm])
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
                    ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#d1d5db")),
                    ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#e5e7eb")),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 7),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 7),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ]
            )
        )
        return table

    def _document_metadata(self, args: dict[str, Any]) -> list[tuple[str, str]]:
        labels = {
            "caseId": "Case ID",
            "case_id": "Case ID",
            "court": "Court / Authority",
            "recipient": "Recipient",
            "jurisdiction": "Jurisdiction",
            "reference": "Reference",
        }
        metadata: list[tuple[str, str]] = []
        seen_labels: set[str] = set()
        for key, label in labels.items():
            value = self._clean_text(args.get(key))
            if value and label not in seen_labels:
                metadata.append((label, value))
                seen_labels.add(label)
        return metadata

    def _parse_sections(self, value: Any) -> list[dict[str, str]]:
        if not isinstance(value, list):
            return []
        sections: list[dict[str, str]] = []
        for item in value:
            if not isinstance(item, dict):
                continue
            heading = self._clean_text(item.get("heading") or item.get("title"))
            body = self._clean_text(item.get("body") or item.get("content"))
            if heading and body:
                sections.append(
                    {
                        "heading": heading,
                        "body": body,
                        "pageBreakBefore": "true" if item.get("pageBreakBefore") is True else "false",
                    }
                )
        return sections

    def _parse_text_list(self, value: Any) -> list[str]:
        if isinstance(value, str):
            cleaned = self._clean_text(value)
            return [cleaned] if cleaned else []
        if not isinstance(value, list):
            return []
        return [cleaned for item in value if (cleaned := self._clean_text(item))]

    def _paragraphs(self, value: str) -> list[str]:
        return [paragraph.strip() for paragraph in re.split(r"\n\s*\n", value) if paragraph.strip()]

    def _filename(self, document_type: str, title: str) -> str:
        stem = re.sub(r"[^a-zA-Z0-9]+", "-", f"{document_type}-{title}").strip("-").lower()
        return f"{stem[:80] or 'veritas-legal-document'}.pdf"

    def _pdf_path(self, artifact_id: UUID) -> Path:
        return self._artifact_directory / f"{artifact_id}.pdf"

    def _metadata_path(self, artifact_id: UUID) -> Path:
        return self._artifact_directory / f"{artifact_id}.json"

    def _clean_text(self, value: Any) -> str:
        return " ".join(str(value or "").replace("\r", "\n").split()) if value is not None else ""

    def _escape(self, value: str) -> str:
        return (
            value.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
        )
